# -*- coding: utf-8 -*-
"""week3-A108060052-余青蓉.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8qs2tw5t1wojAEOZb6SfbfCszHFRrUY
"""

print("Hello World")